// <auto-generated />
using ClubDoorman;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClubDoorman.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250505210758_Banlist")]
    partial class Banlist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ClubDoorman.BlacklistedUser", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BlacklistedUsers");
                });

            modelBuilder.Entity("ClubDoorman.Stats", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlacklistBanned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChatTitle")
                        .HasColumnType("TEXT");

                    b.Property<int>("KnownBadMessage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoppedCaptcha")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
